NUMPY Array

In [2]:
import numpy as np
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
n2= np.array([[10,20,30,40],[30,25,20,15]])
n2

(2, 4)

In [ ]:
type(n2)

numpy.ndarray


**Numpy with Zeros**

In [ ]:
n3= np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n4= np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Numpy array with same Number**

In [ ]:
n5= np.full((3,4),(9))
n5

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
n6= np.full((3,6),7)
n6

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

**Numpy array within a range**

In [ ]:
n7= np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
n8 = np.arange(20,50,5)
n8

array([20, 25, 30, 35, 40, 45])

In [ ]:
n9 = np.arange(60,40,-2)
n9

array([60, 58, 56, 54, 52, 50, 48, 46, 44, 42])

**NUMPY array with Random Number **

In [ ]:
n10 = np.random.randint(10,30)
n10

26

In [ ]:
n11 = np.random.randint(50,200,10)
n11

array([134, 157, 128, 144, 132, 189, 120, 187, 187, 139])

**Numpy array shape check and Change**

In [ ]:
n12= np.array([[1,2,3,4],[9,8,2,4]])
n12

array([[1, 2, 3, 4],
       [9, 8, 2, 4]])

In [ ]:
n12.shape

(2, 4)

In [ ]:
n12.shape= (4,2)
n12

array([[1, 2],
       [3, 4],
       [9, 8],
       [2, 4]])

**Stacking Function in Numpy**


*   Vstack()
*   hstack()
*   column_stack()

In [9]:
nn1= np.array([10,12,15])
nn2=np.array([20,22,23])

In [8]:
np.vstack((nn1,nn2))

array([[10, 12, 15],
       [20, 22, 23]])

In [6]:
np.hstack((nn1,nn2))

array([10, 12, 15, 20, 22, 23])

In [7]:
np.column_stack((nn1,nn2))

array([[10, 20],
       [12, 22],
       [15, 23]])