<a href="https://colab.research.google.com/github/shamiik/numpy/blob/main/numpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy MAtrix**

In [40]:
 import numpy as np
 n1= np.array([[1,2,3],[10,20,30],[50,60,70]])
 n1

array([[ 1,  2,  3],
       [10, 20, 30],
       [50, 60, 70]])

In [41]:
n1[:1]    #acess 1st row

array([[1, 2, 3]])

In [42]:
n1[:,0]   #acess 1st coloumn

array([ 1, 10, 50])

In [43]:
n1[:,2]   #acess 3rd coloumn

array([ 3, 30, 70])

In [44]:
n1[1:]    #acess all row without 1st row

array([[10, 20, 30],
       [50, 60, 70]])

**Transpose Matrix**

In [45]:
n1

array([[ 1,  2,  3],
       [10, 20, 30],
       [50, 60, 70]])

In [46]:
n1.transpose()

array([[ 1, 10, 50],
       [ 2, 20, 60],
       [ 3, 30, 70]])

In [47]:
#Or
np.transpose(n1)

array([[ 1, 10, 50],
       [ 2, 20, 60],
       [ 3, 30, 70]])

**Matrix Multiplication**

In [48]:
n1

array([[ 1,  2,  3],
       [10, 20, 30],
       [50, 60, 70]])

In [53]:
n2= np.array([[90,80,70],[40,30,20],[40,30,20]])
n2

array([[90, 80, 70],
       [40, 30, 20],
       [40, 30, 20]])

In [54]:
n1.dot(n2)

array([[ 290,  230,  170],
       [2900, 2300, 1700],
       [9700, 7900, 6100]])

In [55]:
n2.dot(n1)

array([[4390, 5980, 7570],
       [1340, 1880, 2420],
       [1340, 1880, 2420]])

**Save & Load**

In [61]:
np.save('my_numpy',n1)



In [60]:
n3= np.load('my_numpy.npy')
n3

array([[ 1,  2,  3],
       [10, 20, 30],
       [50, 60, 70]])