<a href="https://colab.research.google.com/github/shamiik/numpy/blob/main/NumpyIntersection%26MAth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Numpy Intersection & Difference`**

In [11]:
import numpy as np
n1 = np.array([10,20,30,40])
n2= np.array([30,40,50,60,70])

In [16]:
np.intersect1d(n1,n2)   #common element of n1 & n2

array([30, 40])

In [8]:
np.setdiff1d(n1,n2) #unique element of n1 (n1 as 1st parameter)

array([10, 20])

In [9]:
np.setdiff1d(n2,n1) #unique element of n2  (n2 as 1st paprameter)

array([50, 60, 70])

**Numpy Array Addition**

In [17]:
n3= np.array([10,20])
n4= np.array([30,40])

In [19]:
np.sum([n3,n4])

100

In [22]:
np.sum([n3,n4],axis=0) #colomn adding

array([40, 60])

In [23]:
np.sum([n3,n4],axis=1) #row adding

array([30, 70])

`Basic Addition in values`

In [24]:
n5= np.array([10,20,30,40])

In [25]:
n5+1

array([11, 21, 31, 41])

In [27]:
n5+5

array([15, 25, 35, 45])

`Basic Subtraction`

In [29]:
n5-1

array([ 9, 19, 29, 39])

`Basic Multiplication`

In [30]:
n5*2

array([20, 40, 60, 80])

`Basic division`

In [31]:
n5/2

array([ 5., 10., 15., 20.])

`Mean Value`

In [34]:
n6= np.array([10,15,20,25,30,35])
np.mean(n6)

22.5

`Standard Deviation`

In [35]:
np.std(n6)

8.539125638299666

`Median`

In [36]:
np.median(n6)

22.5

**`Saving & Loading Numpy Array`**

In [38]:
n7= np.array([10,20,30,40,50,60,70])
np.save('my_last_numpyArray',n7)

In [41]:
n8= np.load('my_last_numpyArray.npy')
n8


array([10, 20, 30, 40, 50, 60, 70])