<a href="https://colab.research.google.com/github/shamiik/numpy/blob/main/NumpyIntersection%26MAth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Numpy Intersection & Difference`**

In [11]:
import numpy as np
n1 = np.array([10,20,30,40])
n2= np.array([30,40,50,60,70])

In [16]:
np.intersect1d(n1,n2)   #common element of n1 & n2

array([30, 40])

In [8]:
np.setdiff1d(n1,n2) #unique element of n1 (n1 as 1st parameter)

array([10, 20])

In [9]:
np.setdiff1d(n2,n1) #unique element of n2  (n2 as 1st paprameter)

array([50, 60, 70])

**Numpy Array Addition**

In [17]:
n3= np.array([10,20])
n4= np.array([30,40])

In [19]:
np.sum([n3,n4])

100

In [22]:
np.sum([n3,n4],axis=0) #colomn adding

array([40, 60])

In [23]:
np.sum([n3,n4],axis=1) #row adding

array([30, 70])